// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// MongoRepo is an autogenerated mock type for the MongoRepo type
type MongoRepo struct {
	mock.Mock
}

// SaveShortUrl provides a mock function with given fields: shortUrl, originUrl, expireAt
func (_m *MongoRepo) SaveShortUrl(shortUrl string, originUrl string, expireAt int64) error {
	ret := _m.Called(shortUrl, originUrl, expireAt)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, int64) error); ok {
		r0 = rf(shortUrl, originUrl, expireAt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
